# Generated by Django 2.1rc1 on 2018-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='Room',
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
