# Generated by Django 2.1rc1 on 2018-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_input', '0003_auto_20181022_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='Contact_No',
            field=models.BigIntegerField(),
        ),
    ]
