# Generated by Django 2.1rc1 on 2018-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_input', '0005_auto_20181022_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
