# Generated by Django 2.1rc1 on 2018-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Room_No',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date prescribed'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Remarks',
            field=models.TextField(max_length=100),
        ),
    ]
