# Generated by Django 2.1rc1 on 2018-10-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20181022_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Contact_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Room_No',
            field=models.IntegerField(),
        ),
    ]
