# Generated by Django 2.1rc1 on 2018-10-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20181022_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Contact_No',
            field=models.IntegerField(max_length=50),
        ),
    ]
